### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Ferscery** [gr8joo/IIAE#2]
Thank you for your work. During my study, I noticed that the number of sketches in the sketchy dataset downloaded with the link you gave is far less than the number of features you extracted. I wonder why this is.

**Comment by gr8joo** [comment]
Hi, thank you for your interest in our work.

I am afraid I misunderstood your question.

If you have already downloaded the features from the [link](http://doi.org/10.5281/zenodo.3890097) and unzipped,
you should be able to find following 4 files (among 8 in total) under 'Data_Pretrained/datasets/SketchyVGG/split1/':
train_sketch_features.npy, test_sketch_features.npy, train_image_features.npy, test_image_features.npy

Those files are composed of many samples of features according to the statistics as follows:

| # of samples (Corresponding file) |               Train                |               Test                | Total  |
| :-------------------------------: | :--------------------------------: | :-------------------------------: | :----: |
|             Sketches              | 61,058 (train_sketch_features.npy) | 14,421 (test_sketch_features.npy) | 75,479 |
|              Photos               | 58,376 (train_image_features.npy)  | 14,626 (test_image_features.npy)  | 73,002 |

Please note that total numbers of samples in the table above and the paper coincide.
I believe you can find the same number of samples, which can be easily verified by checking the shape of those files.
For example,
`tsf = np.load('train_sketch_features.npy'); print('Num of samples:', tsf.shape[0], '/ size of features:', tsf.shape[1])`
`>>> Num of samples: 61058 / size of features: 512`

If you see some different numbers or have some trouble with accessing those files, please let me know.

Thank you.

**Comment by Ferscery** [comment]
Thank you for your reply, you misunderstood my meaning. You mentioned that in the sketchy VGG you gave in [http://doi.org/10.5281/zenodo.3890097](url) (take the training set as an example), there are 14,421 sketches, but in the pixel-level sketchy data set I downloaded in [https://github.com/AnjanDutta/sem-pcyc](url) there are not so many sketches. I want to know why this is.

**Comment by gr8joo** [comment]
Please note that the dataset we use is Sketchy-Extended (which is used by SEM-PCYC as well), not the original Sketchy.
I achieved pixel-level images of the dataset by following SEM-PCYC's [script](https://github.com/AnjanDutta/sem-pcyc/blob/master/download_datasets.sh) which manages downloading & preprocessing the dataset. 

I am not sure how you have collected the dataset.
How many sketches did you find?
Please make sure that you strictly follow their steps to achieve Sketchy-Extended without facing any error when executing the [script](https://github.com/AnjanDutta/sem-pcyc/blob/master/download_datasets.sh).

**Comment by Ferscery** [comment]
Thank you for your patience. I found that I did not download the extended part. I am sorry for the trouble caused to you.
